//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineProductMesEntityu
{
    using System;
    
    
    public sealed class PowerEntity
    {
        
        private int _idx;
        
        private string _pow001;
        
        private string _pow002;
        
        private string _pow003;
        
        private bool _pow004;
        
        private bool _pow005;
        
        private bool _pow006;
        
        private bool _pow007;
        
        private bool _pow008;
        
        private bool _pow009;
        
        private bool _pow010;
        
        private bool _pow011;
        
        private bool _pow012;
        
        private bool _pow013;
        
        private DateTime _pow014;
        
        private string _pow015;
        
        private bool _pow016;
        
        private bool _pow017;
        
        private string _pow018;
        
        private string _pow019;
        
        private string _pow020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>

        public string POW001
        {
            get
            {
                return this._pow001;
            }
            set
            {
                this._pow001 = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string POW002
        {
            get
            {
                return this._pow002;
            }
            set
            {
                this._pow002 = value;
            }
        }

        /// <summary>
        /// 程序编码
        /// </summary>

        public string POW003
        {
            get
            {
                return this._pow003;
            }
            set
            {
                this._pow003 = value;
            }
        }

        /// <summary>
        /// 查询
        /// </summary>

        public bool POW004
        {
            get
            {
                return this._pow004;
            }
            set
            {
                this._pow004 = value;
            }
        }

        /// <summary>
        /// 新增
        /// </summary>

        public bool POW005
        {
            get
            {
                return this._pow005;
            }
            set
            {
                this._pow005 = value;
            }
        }

        /// <summary>
        /// 删除
        /// </summary>

        public bool POW006
        {
            get
            {
                return this._pow006;
            }
            set
            {
                this._pow006 = value;
            }
        }

        /// <summary>
        /// 编辑
        /// </summary>

        public bool POW007
        {
            get
            {
                return this._pow007;
            }
            set
            {
                this._pow007 = value;
            }
        }

        /// <summary>
        /// 送审
        /// </summary>

        public bool POW008
        {
            get
            {
                return this._pow008;
            }
            set
            {
                this._pow008 = value;
            }
        }

        /// <summary>
        /// 审核
        /// </summary>

        public bool POW009
        {
            get
            {
                return this._pow009;
            }
            set
            {
                this._pow009 = value;
            }
        }

        /// <summary>
        /// 保存
        /// </summary>

        public bool POW010
        {
            get
            {
                return this._pow010;
            }
            set
            {
                this._pow010 = value;
            }
        }

        /// <summary>
        /// 取消
        /// </summary>

        public bool POW011
        {
            get
            {
                return this._pow011;
            }
            set
            {
                this._pow011 = value;
            }
        }

        /// <summary>
        /// 注销
        /// </summary>

        public bool POW012
        {
            get
            {
                return this._pow012;
            }
            set
            {
                this._pow012 = value;
            }
        }
        
        /// <summary>
        /// 运行
        /// </summary>
                 
        public bool POW013
        {
            get
            {
                return this._pow013;
            }
            set
            {
                this._pow013 = value;
            }
        }
        
        /// <summary>
        /// 日期
        /// </summary>
                 
        public DateTime POW014
        {
            get
            {
                return this._pow014;
            }
            set
            {
                this._pow014 = value;
            }
        }
        
        /// <summary>
        /// 操作人
        /// </summary>
                 
        public string POW015
        {
            get
            {
                return this._pow015;
            }
            set
            {
                this._pow015 = value;
            }
        }
        
        /// <summary>
        /// 打印
        /// </summary>
                 
        public bool POW016
        {
            get
            {
                return this._pow016;
            }
            set
            {
                this._pow016 = value;
            }
        }
        
        /// <summary>
        /// 导出
        /// </summary>
                 
        public bool POW017
        {
            get
            {
                return this._pow017;
            }
            set
            {
                this._pow017 = value;
            }
        }
        
        // 
        public string POW018
        {
            get
            {
                return this._pow018;
            }
            set
            {
                this._pow018 = value;
            }
        }
        
        // 
        public string POW019
        {
            get
            {
                return this._pow019;
            }
            set
            {
                this._pow019 = value;
            }
        }
        
        // 
        public string POW020
        {
            get
            {
                return this._pow020;
            }
            set
            {
                this._pow020 = value;
            }
        }
    }
}
